Repository techworkersco/techworkersco.github.io, pull requests merged in 2020-05, with the labels that each got.

#23 Setup mailchimp subscribe form
  _includes/mailchimp_signup.html
  _layouts/standalone.html
  index.md
  subscribe.md
Labels: enhancement

#39 [Archive] minor style updates
  archive.md
Labels: enhancement

#38 [Danger] new rules + update gems
  Dangerfile
  Gemfile.lock
Labels: enhancement

#48 [Danger] Improve spell-checker
  Dangerfile
Labels: enhancement

#50 [Docs] Improve documentation
  .github/CONTRIBUTING.md
  .github/DOCUMENTATION.md
  Dangerfile
  README.md
Labels: enhancement

#57 [Docs] update with schedule + tweets
  .github/CODE_OF_CONDUCT.md
  .github/DOCUMENTATION.md
  README.md
Labels: documentation

#63 [Docs] Process, schedule, and checklist
  .github/DOCUMENTATION.md
  .github/PROCESS.md
Labels: documentation

#77 Improve "latest" text on homepage
  _includes/post_entry.html
  index.md
Labels: enhancement

#78 Update DOCUMENTATION.md
  .github/DOCUMENTATION.md
Labels: documentation

#83 Issue #3 (5/29/2020)
  _posts/2020-05-29-issue-3.md
  img/vol-2-issue-3-header.jpg
Labels: merge on friday morning
